# Simple Neural Networks
** November 2017 **

** Andrew Riberio @ [AndrewRib.com](http://www.andrewrib.com) **

Simple Neural Networks 

** Note: ** This notebook contains interactive elements and certain latex snippets that will not render in github markdown. 
You must run this notebook on your local Jupyter notebook environment for interactive elements or render or if you wish to render just the latex by using the url of this repo with the [online NBViewer](https://nbviewer.jupyter.org/).

## Libraries

In [263]:
import numpy as np
import tensorflow as tf
#Interactive Components
from ipywidgets import interact

## Learning XOR
$$
\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\overset{∧}{\rightarrow}
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$

$$
w^\intercal 
relu(X^\intercal W + c)+b = \begin{bmatrix} 0 & 0 & 0 & 1 \end{bmatrix}^\intercal
$$

Here we simply implement the results in section 6.1 of the book. We are not really learning XOR here. We are using the results of some learning process to show that given some matrix X, we can transform it into a vector which represents the XOR operation on each row of X. 

The final result we've achieved by hand is: 

$$
\begin{bmatrix} 
0 & 1
\end{bmatrix}^\intercal 
relu\left(\begin{bmatrix} 
1 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix} 
1 & 1 \\
1 & 1 \\
1 & 1 \\
\end{bmatrix}
+ 
\begin{bmatrix} 
0 \\
-1  \\
\end{bmatrix}
\right)^\intercal +0 = 1
$$



In [314]:
W = np.matrix([[1,1],[1,1]])
X = np.matrix([[1,1]])
c = np.matrix([0,-1])
w = np.matrix([1,-2])
b = 0

#w*relu(X*W.T+c)

#relu(X*W+c)*w.T

w*relu(X*W+c).T+b

matrix([[0]])

In [290]:
X*W +c

matrix([[2, 1],
        [1, 0]])

In [149]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
tf.matmul(np.matrix([3,4,5]),np.matrix([3,4,5]).T).eval()

array([[50]])

In [151]:
3*3 + 4*4 + 5*5

50

In [ ]:

X = tf.placeholder(tf.float32, [None, 3],name='input')
W1 = tf.Variable(tf.random_uniform([3,2], -1, 1),name='W1')
W2 = tf.Variable(tf.random_uniform([1,2], -1, 1),name='W2')

t0 = tf.matmul(X, W1)
t1 = tf.transpose(t0)

y = tf.nn.relu(tf.matmul(W2,t1),name='relu')
y_ = tf.placeholder(tf.float32, [None, 1])

cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))


train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

batch_xs = np.matrix([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
batch_ys = np.matrix([0,1,1,0]).T

sess.run(train_step, feed_dict={X: batch_xs, y_: batch_ys}) 

sess.run(W1*tf.transpose(W2))

In [272]:
np.matrix([1,1/2,1/2,1]).T*np.matrix([1,1])

matrix([[ 1. ,  1. ],
        [ 0.5,  0.5],
        [ 0.5,  0.5],
        [ 1. ,  1. ]])

In [86]:
tf.t

AttributeError: module 'tensorflow' has no attribute 't'

In [183]:
def relu(z):
    return np.maximum(0,z)

def linLayer(x,w,b):
    return x.T*w + b

# x: 2 by 4
# W: 2 by 2
# c: 2 by 1
# w: 2 by 1
# b: scalar

def fullNetwork(x,W,c,w,b):
    h = relu( linLayer(W,x,c) )
    return linLayer(w, h, b)

In [70]:
W = np.matrix([[1,0],[1,0],[1,0]])
X = np.matrix([0,1,1])
w = np.matrix([-1,-1]).T


#w.T*relu(X*W).T
X.shape

(1, 3)

In [72]:
relu(np.matrix([3,-1]))

matrix([[3, 0]])

In [ ]:
print("x.T\n")
print(x.T)
print("\nx.T*W\n")
print(x.T*W)

In [19]:
linLayH = linLayer(W,x,c)
print("x.T*W + c\n")
print(linLayH.T)

x.T*W + c

[[ 0 -1]
 [ 1  0]
 [ 1  0]
 [ 2  1]]


In [20]:
h = relu( linLayH )
print("relu( x.T*W + c )\n")
print(h.T)

relu( x.T*W + c )

[[0 0]
 [1 0]
 [1 0]
 [2 1]]


In [21]:
w = np.matrix([1,-2]).T
b = 0

f = linLayer(w, h, b)

print("w.T*relu( x.T*W + c )+b\n")
print(f.T)

w.T*relu( x.T*W + c )+b

[[0]
 [1]
 [1]
 [0]]


In [26]:
fullNetwork(np.matrix([0,0]).T,W,c,w,b)

matrix([[0]])

If learning XOR was a linear transformation there would be an M such that x.T * M = [ 0,1,1,0]. There is no such M, however. Below you will find an interactive section for exploring M space ( 1 by 2 matrix ). 

In [8]:
def exploreM(m1=1,m2=-2):
    M = np.matrix([m1,m2]).T
    print("M:")
    print(M)
    print("\nx:")
    print(x.T)
    print("\nDesired x.T * M:")
    print(np.matrix([0,1,1,0]).T)
    print("\nx.T * M:")
    print(x.T*M)

interact(exploreM,m1=[-10,10],m2=[-10,10])

M:
[[ 1]
 [-2]]

x:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Desired x.T * M:
[[0]
 [1]
 [1]
 [0]]

x.T * M:
[[ 0]
 [-2]
 [ 1]
 [-1]]


<function __main__.exploreM>

## Representing AND
We'd like to transform matrix X representing all possible values for the opperands of AND( ∧ ) into a vector representing the value of applying AND to those opperands:

$$
\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\overset{∧}{\rightarrow}
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$

$$
w^\intercal 
relu(X^\intercal W + c)+b = \begin{bmatrix} 0 & 0 & 0 & 1 \end{bmatrix}^\intercal
$$

As you can see, the task is to find matricies W,w,c, and scalar b which transforms our x matrix into the solution desired. Let's try to do this by hand to explore how the various variables behave in respect to transforming X.

We first look at how a matrix of ones is transformed by different values of W. 

###  W

In [10]:
def wInt(w1,w2,w3,w4):
    W = np.matrix([[w1,w2],
                   [w3, w4]])
    print(x.T*W)
    
interact(wInt,w1=[-5,5],w2=[-5,5],w3=[-5,5],w4=[-5,5])

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


<function __main__.wInt>

From experimenting above we can see that: 

* w1: Modifies the first column values. 
* w3: Modifies the first column values. 


* w2: Modifies the second column values
* w4: Modifies the second column values

Now let's do the same experiment with the x matrix set to the desired x. 

In [11]:
x = np.matrix([[0,0,1,1],[0,1,0,1]])
interact(wInt,w1=[-5,5],w2=[-5,5],w3=[-5,5],w4=[-5,5])

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


<function __main__.wInt>

From experimenting above we can see that: 

* w1: Modifies the first column values in **the last two rows**. 
* w2: Modifies the second column values in **the last two rows**.


* w3: Modifies the first column values in **the second and forth rows**.
* w4: Modifies the second column values in **the second and forth rows**.

By experimenting with the applet above, we can find a matrix that makes the last column distinctly larger than all others. Since we'd like to transform this matrix to [0,0,0,1], this is a property we need. I found a W matrix of the form [0,1],[0,1] that seems to do the job. 

In [12]:
W = np.matrix([[0,1],[0,1]])
print(x.T*W)

[[0 0]
 [0 1]
 [0 1]
 [0 2]]


### c
C acts as a sort of filter on W. We can use this to get rid of the 1's above and keep the last row a 1. 

In [13]:
c = np.matrix([0,-1]).T
linLayH = linLayer(W,x,c)
print("x.T*W + c\n")
print(linLayH.T)

x.T*W + c

[[ 0 -1]
 [ 0  0]
 [ 0  0]
 [ 0  1]]


Nice! We can see that when applying an element wise relu will get us what we'd like. 

In [14]:
h = relu(linLayH)
print(h.T)

[[0 0]
 [0 0]
 [0 0]
 [0 1]]


Now we must figure out the other variable values to flatten this matrix to a vector. 

### w
Given the results from above, we know we can ignore b and just find a w that turns the matrix above to a vector. We do that with a column vector [0,1].T

In [15]:
w = np.matrix([0,1]).T
fn = linLayer(w, h, 0)
print(fn.T)

[[0]
 [0]
 [0]
 [1]]


The final result we've achieved by hand is: 

$$
\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\overset{∧}{\rightarrow}
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$

$$
\begin{bmatrix} 
0 \\
1  \\
\end{bmatrix}^\intercal 
relu(\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\begin{bmatrix} 
0 & 1 \\
0 & 1 \\
\end{bmatrix}
+ 
\begin{bmatrix} 
0 \\
-1  \\
\end{bmatrix}
)^\intercal +0 = \begin{bmatrix} 0 & 0 & 0 & 1 \end{bmatrix}
$$



The final result we've achieved by hand is: 

$$
\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\overset{∧}{\rightarrow}
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$

$$
\begin{bmatrix} 
0 \\
1  \\
\end{bmatrix}^\intercal 
relu(\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\begin{bmatrix} 
0 & 1 \\
0 & 1 \\
\end{bmatrix}
+ 
\begin{bmatrix} 
0 \\
-1  \\
\end{bmatrix}
)^\intercal +0 = \begin{bmatrix} 0 & 0 & 0 & 1 \end{bmatrix}
$$



In our next notebook **Neural Boolean Connectives 2** we will explore the case when we are given an additional target vector which contains a label for each row of X representing the result of the boolean operation to be learned. In the case of AND, we'd have: 

$$
x = \begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
,y = 
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$